# Generated by Django 4.0.3 on 2022-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0002_register_confirmation_register_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=55)),
                ('repassword', models.CharField(max_length=55)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
