# Generated by Django 4.0.3 on 2022-03-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0004_login_register_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('Femaile', 'female')], max_length=20)),
                ('acres', models.IntegerField()),
                ('kharif', models.CharField(choices=[('RICE', 'rice'), ('MAIZE', 'maize'), ('MILLET', 'millet'), ('RAGI', 'ragi'), ('PULSES', 'pulses'), ('SOYABEAN', 'soyabean'), ('GROUND NUT', 'ground nut')], max_length=20)),
                ('rabi', models.CharField(choices=[('WHEAT', 'wheat'), ('BARLEY', 'barley'), ('OATS', 'oats'), ('GRAM', 'gram'), ('MUSTARD', 'mustard')], max_length=20)),
                ('loan', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=10)),
            ],
        ),
    ]
