# Generated by Django 4.0.3 on 2022-03-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
