# Generated by Django 4.0.3 on 2022-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0006_register_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('tcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('AGRICULTURE', 'agriculture'), ('AQUACULTURE', 'aquaculture')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
