# Generated by Django 4.0.3 on 2022-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('seeds_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=32)),
                ('s_category', models.CharField(choices=[('AGRICULTURE', 'agriculture'), ('AQUACULTURE', 'aquaculture')], max_length=20)),
                ('s_quantity', models.IntegerField()),
                ('s_price', models.FloatField()),
            ],
        ),
    ]
